# # UART Shell
# CONFIG_SHELL=y
# CONFIG_FILE_SYSTEM_SHELL=y

# RTT Shell
CONFIG_SHELL=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_SHELL_BACKEND_RTT=y
CONFIG_FILE_SYSTEM_SHELL=y

# Log UART
# CONFIG_LOG_INFO_COLOR_GREEN=y
# CONFIG_LOG_MODE_MINIMAL=y
# CONFIG_LOG_MODE_DEFERRED=y
# CONFIG_LOG_MODE_OVERFLOW=y
# CONFIG_LOG_BUFFER_SIZE=2048
# CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=2048

# Log RTT
# CONFIG_LOG_MODE_MINIMAL=n
# CONFIG_RTT_CONSOLE=y
# CONFIG_USE_SEGGER_RTT=y
# CONFIG_LOG_BACKEND_RTT=y
# CONFIG_LOG_BACKEND_UART=n
# CONFIG_LOG_BACKEND_RTT_BUFFER_SIZE=2048
# CONFIG_LOG_BACKEND_RTT_MESSAGE_SIZE=256
# CONFIG_LOG_BACKEND_RTT_MODE_OVERWRITE=y
# CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=2048

# Network Logging
# CONFIG_NET_LOG=y
# CONFIG_NET_BUF_LOG=y
# CONFIG_NET_BUF_LOG_LEVEL_DBG=y
# CONFIG_NET_SOCKETS_LOG_LEVEL_DBG=y
# CONFIG_NET_HTTP_LOG_LEVEL_DBG=y
# CONFIG_NET_BUF_POOL_USAGE=y
# CONFIG_NET_BUF_SIMPLE_LOG=y

# Debugging
CONFIG_DEBUG=y
# CONFIG_DEBUG_OPTIMIZATIONS=y
# CONFIG_RESET_ON_FATAL_ERROR=n
# CONFIG_THREAD_NAME=y
# CONFIG_THREAD_MONITOR=y
# CONFIG_THREAD_ANALYZER=y
# CONFIG_THREAD_ANALYZER_ISR_STACK_USAGE=y
# CONFIG_THREAD_ANALYZER_USE_LOG=y
# CONFIG_THREAD_ANALYZER_AUTO=y
# CONFIG_DEBUG_THREAD_INFO=y
# CONFIG_THREAD_STACK_INFO=y
# CONFIG_DEBUG_COREDUMP=y
# CONFIG_DEBUG_COREDUMP_BACKEND_LOGGING=y
# CONFIG_DEBUG_COREDUMP_MEMORY_DUMP_MIN=y
# CONFIG_MULTIPLEXER_LOG_LEVEL_DBG=y
# CONFIG_LOG_DEFAULT_LEVEL=3
