# Newlib C
CONFIG_NEWLIB_LIBC=y

# Reset Reason and Reboot
CONFIG_HWINFO=y
CONFIG_REBOOT=y

# Power Management
CONFIG_PM_DEVICE=n

# initialize stack areas with a known value (0xaa) before they are first used

# Flash operations.
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y
# CONFIG_FPROTECT=n

# I2C
CONFIG_I2C=y

# Networking
CONFIG_NETWORKING=y
CONFIG_NET_NATIVE=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_OFFLOAD=y
CONFIG_NET_SOCKETS_POSIX_NAMES=y
CONFIG_NET_TCP=y
CONFIG_NET_UDP=y
CONFIG_NET_IPV6=y
CONFIG_NET_IPV4=y
CONFIG_NET_DHCPV4=y

# Enable the DNS resolver
CONFIG_DNS_RESOLVER=y
CONFIG_NET_SOCKETS_DNS_TIMEOUT=20000

# Networking Debug
CONFIG_NET_LOG=y
CONFIG_NET_SHELL=y

# SNTP
CONFIG_POSIX_CLOCK=y
CONFIG_SNTP=y

# Set Stack Size
## Needs to be larger than expected routes download
CONFIG_MAIN_STACK_SIZE=81920

# Bootloader
CONFIG_BOOTLOADER_MCUBOOT=n
CONFIG_DFU_TARGET=n

# Image Manager
CONFIG_IMG_MANAGER=y
CONFIG_MCUBOOT_IMG_MANAGER=y
CONFIG_IMG_ERASE_PROGRESSIVELY=y

# Temp fix for unaligned TFM partitions with MCUBoot
# CONFIG_TFM_CMAKE_BUILD_TYPE_RELEASE=n

# Logging
CONFIG_LOG=y
CONFIG_LOG_BACKEND_NET=y
CONFIG_LOG_BACKEND_NET_SERVER="20.122.204.127:514"
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_BACKEND_NET_AUTOSTART=n
CONFIG_LOG_MODE_MINIMAL=y

# Debug Mode
CONFIG_DEBUG=y
CONFIG_DEBUG_OPTIMIZATIONS=n
CONFIG_DEBUG_INFO=n
