# Import requirements for nRF9160 Feather Examples and Drivers
manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: ncs
      revision: v3.0.1
      import:
         name-allowlist:
          - cmsis
          - cmsis-dsp
          - cmsis-nn
          - hal_nordic
          - littlefs
          - mbedtls
          - mcuboot
          - nrf_hw_models
          - nrfxlib
          - oberon-psa-crypto
          - picolibc
          - qcbor
          - segger
          - tinycrypt
          - trusted-firmware-m
          - zcbor
          - zephyr

    # Multiplexer Driver
    - name: multiplexer
      url: https://github.com/justins-engineering/zephyr-multiplexer
      revision: main
      path: multiplexer

  self:
    path: app
