# Import requirements for nRF9160 Feather Examples and Drivers
manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: ncs
      revision: v3.4.0
      import:
         name-allowlist:
          - cmsis_6
          - hal_nordic
          - mbedtls
          - mcuboot
          - nrfxlib
          - oberon-psa-crypto
          - segger
          - tf-psa-crypto
          - trusted-firmware-m
          - zcbor
          - zephyr

    # Multiplexer Driver
    - name: multiplexer
      url: https://github.com/justins-engineering/zephyr-multiplexer
      revision: main
      path: multiplexer

  self:
    path: app
